package com.java;

import java.util.Random;

public class AutogeneratedNumber {

	public static void main(String[] args) {
	
		autogenerateNumber();
		

	}
		public static CharSequence autogenerateNumber() {
		    Random rd = new Random(); 
		    int[] a = new int[10];
		    
		  for (int i = 0; i < 10; i++) {
		        a[i] = rd.nextInt(10);
		        System.out.println("In first loop the autogeneration is " + a[i]);
		    } 

		    // Build the mobile number as a String
		    StringBuilder mobileNumber = new StringBuilder();
		    for (int i = 0; i < 10; i++) {
		    	System.out.println("Before append" + i);
		        mobileNumber.append(a[i]); 
		    }

		    System.out.println("The Mobile number is: " + mobileNumber.toString());

		    return mobileNumber.toString();  // Return as CharSequence
		}
			
	}
	
