
package Selenium.TestOne;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.testng.Assert;



public class BaseClass {
	
	
	
	WebDriver driver;
	
	public void login(WebDriver driver) throws Exception {
		
		 driver.findElement(By.id("userName_login")).sendKeys("masters");
		 driver.findElement(By.id("password_login")).sendKeys("Sairam@123");
		 driver.findElement(By.xpath("//button[text()='Continue']")).click();
		 driver.findElement(By.xpath("//img[@id='sideLogo_img']")).click();
		 Thread.sleep(2000); 
	}
	
	   
	public void ClickMenu(WebDriver driver) throws Exception {
	    
		driver.findElement(By.xpath("//div[@id='style-1']//following-sibling::li[@id='partsOpen']")).click();
		Thread.sleep(2000);
		driver.findElement((By.xpath("//div[@class='scrollbar']//following::li[@id='partsOpen']//following::li[2]"))).click();
		
	}

	public void CompareTitle(WebDriver driver, String ActualTitleName) {
		
		 String Title = driver.getTitle();
		 System.out.println("Titile name is " + Title);
		 String TitleName = ActualTitleName; 
		 if(Title.equals(TitleName)) {
			 Assert.assertTrue(true);
			 System.out.println("It is:" +ActualTitleName+ " screen"); 
		 }
		
		 
	}
	  
	       
public void CheckboxCheckandUncheck(WebDriver driver) throws Exception {
	
  Thread.sleep(2000);
  driver.findElement(By.xpath("(//div[@class='icheckbox_square-blue']//following::ins)[1]")).click();
  driver.findElement(By.xpath("(//div[@class='icheckbox_square-blue']//following::ins)[1]")).isSelected();
  
}

public void VendorDetailsEntry(WebDriver driver) throws Exception {
	
	driver.findElement(By.xpath("//i[@class='fa fa-plus-square']")).click();
	Thread.sleep(2000);
	driver.findElement(By.xpath("//input[@id='vendorName']")).sendKeys(autogeneratedString());
	
	driver.findElement(By.xpath("//input[@id='mobileNo']")).sendKeys("789999999");
	Thread.sleep(2000);
	driver.findElement(By.xpath("//i[@class='fa fa-times-circle customClose']")).click();
	
	
	
}

public String autogenerateNumber() {
    Random rd = new Random();
    int[] a = new int[10];
     
   for (int i = 0; i < 5; i++) {
        a[i] = rd.nextInt(10);
    } 

    // Build the mobile number as a String
    StringBuilder mobileNumber = new StringBuilder();
    for (int i = 0; i < 10; i++) {
        mobileNumber.append(a[i]); 
    }

    System.out.println("The Mobile number is: " + mobileNumber.toString());

    return mobileNumber.toString();  // Return as CharSequence
}
	

public  String autogeneratedString() {
	
	String characters = "abcdefghijklmnopqrstuvwxyz";
	
	int TotalLen = 5;
	
	Random rand = new Random();
	
	StringBuilder sb = new StringBuilder();
	
	for(int i=0; i<TotalLen; i++) {
		
		int newrand = rand.nextInt(TotalLen);
		System.out.println(newrand); 
		char newchar = characters.charAt(newrand);
		System.out.println(newchar);
	
	  sb.append(newchar);
	}
	
	    //return sb.toString();
	return sb.toString();
	    
	    
	

	}

public void excelinward(WebDriver driver) throws Exception {
	
	

	SeleniumExcel excel = new SeleniumExcel();
	excel.Excelutils("C:\\Users\\Intel\\Desktop\\Partname.xlsx", "Sheet1");
	
	int TotalRows = excel.rowcount(); 
	System.out.println(TotalRows);

	for (int i = 1; i < TotalRows; i++) {

		String partname = excel.getCellCount(i, 0);
		String qty = excel.getCellCount(i, 1); 
		String price = excel.getCellCount(i, 2);
		driver.findElement(By.xpath("//input[@id='partname']")).sendKeys(partname);
		driver.findElement(By.id("quantity")).sendKeys(qty);
		driver.findElement(By.id("partprice")).sendKeys(price);
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//i[@class='fa fa-plus'])[1]")).click();

	} 
	

}
	
 public void partNosEnter(WebDriver driver) {
	 
	//input[@class='myInput partNumbers ui-autocomplete-input']
	 String[] partNos = {"A123", "B234", "C456", "D444", "E9999", "T3333"};
	 
	 List<WebElement> list = driver.findElements(By.xpath("//input[@class='myInput partNumbers ui-autocomplete-input']"));
	 
	 for(int i=0; i<list.size(); i++) {
		 if(i<partNos.length) {
			 
			 list.get(i).sendKeys(partNos[i]);
			  
		 }
		 
	 }
	 
	 
 }
 
 public void SellingpriceAdd(WebDriver driver) {
	 
	 List<WebElement> qty = driver.findElements(By.xpath("//input[@class='validatingdecimal']"));
	 
	 String qtyvalue = "10";
	 
	 for(int i = 0; i<qty.size(); i++) {
		  
		 if(1 <qtyvalue.length()) { 
			 
			// driver.findElement(By.xpath("(//div[@class='price_amount selling_input_left']//span)[1]")).click();
			 
			 System.out.println(qtyvalue);
			  
			 qty.get(i).sendKeys(qtyvalue);
			  
		 } 
		 
		 
	 }
 }
 
 
 public void moverightside(WebDriver driver) {
	 
	 driver.findElement(By.id("discountTotal")).click();
	 driver.findElement(By.xpath("//th[contains(text(),'Selling Price') ]")).click();
	 
	
	 
 }

 public void clicksubmittButton(WebDriver driver) {
	 
	 driver.findElement(By.id("inwardButtonId")).click();
 }
 
 public void EnterBillNo(WebDriver driver) {
	 
	 driver.findElement(By.xpath("(//input[@class='input__field input__field--nao main_input form-control insurance1 '])[3]")).sendKeys(autogenerateNumber());
 }

 public void SelectCalender(WebDriver driver) {
	 
	 //calanderdate select
	 driver.findElement(By.xpath("(//span[@class='input input--nao']//input[2])[1]")).click();
	 driver.findElement(By.xpath("/html/body/div[7]/div[2]/div/div[2]/div/span[6]")).click();
 }
 
 public void checkThePaymentsTabIsDisplayedorNot(WebDriver driver) {
	 
	  WebElement PaymentsTab = driver.findElement(By.xpath("//a[text()='Payments']"));
	  
	  if(PaymentsTab.isDisplayed()) {
		  
		  driver.findElement(By.xpath("(//button[@class='close'])[3]")).click();
	  }
	 
 } 
 
 public void refresh() {
	 
	 driver.navigate().refresh();
 }
 
	public ArrayList<WebElement> StorePartDetails(WebDriver driver) {

		ArrayList<WebElement> storeElement = new ArrayList<>();

		storeElement.add(driver.findElement(By.xpath("//td[@class='part_no active_row']")));
		storeElement.add(driver.findElement(By.xpath("//td[@class='qoh active_row']")));

		for (WebElement elements : storeElement)
			System.out.println("Array list elements are " + elements.getText());
		return storeElement;
	 
	 
 }
 
 public void CheckStockDetails(WebDriver driver) throws Exception { 
	 
	 SeleniumExcel excel = new SeleniumExcel();
	 excel.Excelutils("C:\\Users\\Intel\\Desktop\\Partname.xlsx", "Sheet1");	
		int TotalRows = excel.rowcount(); 
		System.out.println(TotalRows);
		for (int i = 1; i < TotalRows; i++) {
			String partname = excel.getCellCount(i, 0); 
			Thread.sleep(2000);
			WebElement PartNames = driver.findElement(By.xpath("//input[@id='searchText'] "));
			PartNames.sendKeys(partname);
			StorePartDetails(driver);		
			Thread.sleep(2000);
			PartNames.clear();
			
		}
		}
			
 public void NavigateToSellProducts(WebDriver driver) {
	 
	 driver.findElement(By.xpath("//img[@class='halfLogo']")).click();	 
	 driver.findElement(By.xpath("//span[contains(text(),'Sell Products')]")).click();
	 
 }
 
 public void sellProductsButtonclick(WebDriver driver) {
	
	 driver.findElement(By.xpath("//button[@class='btn btn-primary sellProducts titleBar']")).click();
 }
 
 public void selectSellProductParts() throws Exception {
	 
	 SeleniumExcel excel = new SeleniumExcel();
	 excel.Excelutils("C:\\Users\\Intel\\Desktop\\Partname.xlsx", "Sheet1");	
		int TotalRows = excel.rowcount(); 
		System.out.println(TotalRows);
		for (int i = 1; i < TotalRows; i++) {
			String partname = excel.getCellCount(i, 0); 
			Thread.sleep(2000);
			WebElement PartNames = driver.findElement(By.xpath("//input[@id='searchText_all']"));
			PartNames.sendKeys(partname);
			
			
		
			Thread.sleep(2000);
			PartNames.clear();
		
		}
		
 }
 
}
 
 
 
 
 
 

	







